name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PREFIX: "/usr/local/cross"
  TARGET: "x86_64-elf"
  CROSS_PATH: "/usr/local/cross/x86_64-elf"
  SYSROOT: "$HOME/sysroot/"

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update PATH
      run: echo $PREFIX/bin >> $GITHUB_PATH

    - name: Print Path
      run: echo $GITHUB_PATH && echo $PATH
      
    - name: Install dependencies
      run: | 
        sudo apt-get update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo nasm xorriso mtools python3 python3-pip python3-setuptools python3-wheel ninja-build
        pip3 install --user meson
    
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: root suid tar because github actions doesnt support sudo on cache
      run: sudo chown root:root /bin/tar && sudo chmod u+s /bin/tar
    
    - name: Cache cross compiler
      id: cache-compiler
      uses: actions/cache@v3
      with:
        path: /usr/local/cross
        key: ${{ runner.os }}-cross-compiler
        restore-keys: |
          ${{ runner.os }}-cross-compiler

    - name: Compile cross compiler
      if: steps.cache-compiler.outputs.cache-hit != 'true'
      run: |
        chmod +x $HOME/work/NightOS64/NightOS64/config.sh
        chmod +x headers.sh
        chmod +x default-host.sh
        sudo -E PATH="$PATH" ./headers.sh
        cd $HOME/work/NightOS64/NightOS64
        mkdir -p /tmp/cross-compiler
        cd /tmp/cross-compiler
        wget https://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.gz
        tar -xzf binutils-2.42.tar.gz
        
        cd binutils-2.42/
        sudo git apply $HOME/work/NightOS64/NightOS64/binutils.patch
        cd ..
        
        mkdir build-binutils
        cd build-binutils
        ../binutils-2.42/configure --target=$TARGET --prefix=$PREFIX --with-sysroot --disable-nls --disable-werror
        sudo make -j4
        sudo make install

        cd /tmp/cross-compiler
        which -- $TARGET-as || echo $TARGET-as is not in the PATH

        wget https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.gz
        tar -xzf gcc-14.1.0.tar.gz
        
        cd gcc-14.1.0/
        sudo git apply $HOME/work/NightOS64/NightOS64/gcc.patch
        cd ..
        
        mkdir build-gcc
        cd build-gcc
        ../gcc-14.1.0/configure --target=x86_64-nightos --prefix="$PREFIX" --with-sysroot=$SYSROOT --enable-languages=c,c++ --enable-shared --enable-linker-build-id --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-checking=release --enable-default-pie
        sudo make all-gcc -j4
        sudo make all-target-libgcc -j4
        sudo make install-gcc
        sudo make install-target-libgcc

    - name: Run build
      run: |
        chmod +x default-host.sh
        chmod +x build_lib.sh
        sudo -E PATH="$PATH" ./build_lib.sh
        chmod +x headers.sh
        chmod +x build.sh
        ./build.sh

    - name: Upload ISO
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: nightos.iso
        # A file, directory or wildcard pattern that describes what to upload
        path: myos.iso
        # The desired behavior if no files are found using the provided path.

    - name: Upload binary
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: nightos.kernel
        # A file, directory or wildcard pattern that describes what to upload
        path: nightos.kernel
        # The desired behavior if no files are found using the provided path.

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qemu-system

      - uses: actions/download-artifact@master
        with:
          name: nightos.iso

      - name: Run qemu
        run: qemu-system-x86_64 -cdrom myos.iso -nographic -monitor stdio -serial file:serial.txt -d int -no-reboot -m 512m -M smm=off

      - name: Print serial output
        run: cat serial.txt


