name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PREFIX: "/usr/local/cross"
  TARGET: "x86_64-elf"
  CROSS_PATH: "/usr/local/cross/x86_64-elf"
  SYSROOT: "$HOME/sysroot/"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update PATH
      run: echo $PREFIX/bin >> $GITHUB_PATH

    - name: Print Path
      run: echo $GITHUB_PATH && echo $PATH
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo nasm xorriso mtools
    
    - uses: actions/checkout@v4

    - name: root suid tar because github actions doesnt support sudo on cache
      run: sudo chown root:root /bin/tar && sudo chmod u+s /bin/tar
    
    - name: Cache cross compiler
      id: cache-compiler
      uses: actions/cache@v3
      with:
        path: /usr/local/cross
        key: ${{ runner.os }}-cross-compiler
        restore-keys: |
          ${{ runner.os }}-cross-compiler

    - name: Compile cross compiler
      if: steps.cache-compiler.outputs.cache-hit != 'true'
      run: |
        mkdir -p /tmp/cross-compiler
        cd /tmp/cross-compiler
        wget https://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.gz
        tar -xzf binutils-2.42.tar.gz
        mkdir build-binutils
        cd build-binutils
        ../binutils-2.42/configure --target=$TARGET --prefix=$PREFIX --with-sysroot --disable-nls --disable-werror
        sudo make -j4
        sudo make install

        cd /tmp/cross-compiler
        which -- $TARGET-as || echo $TARGET-as is not in the PATH

        wget https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
        tar -xzf gcc-13.2.0.tar.gz
        
        mkdir build-gcc
        cd build-gcc
        ../gcc-13.2.0/configure --target=$TARGET --prefix=$PREFIX --disable-nls --enable-languages=c,c++ --without-headers
        sudo make all-gcc -j4
        sudo make all-target-libgcc -j4
        sudo make install-gcc
        sudo make install-target-libgcc

    - name: Run build
      run: |
        chmod +x config.sh
        chmod +x default-host.sh
        chmod +x build_lib.sh
        sudo -E PATH="$PATH" ./build_lib.sh
        chmod +x headers.sh
        ./headers.sh
        chmod +x build.sh
        ./build.sh

    - name: Upload ISO
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: nightos.iso
        # A file, directory or wildcard pattern that describes what to upload
        path: myos.iso
        # The desired behavior if no files are found using the provided path.

    - name: Upload binary
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: nightos.kernel
        # A file, directory or wildcard pattern that describes what to upload
        path: nightos.kernel
        # The desired behavior if no files are found using the provided path.